### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tgtgcuh** [Qbox-project/qb-core#38]
### Summary

I Cant Open Qb-phone After Closing it 

### Reproduction

I Opened The Phone Then Closed It But THe Cursor still shows then i cant move or open it again ike its still open

Everything elses is good

### Expected behavior

It To Open And Close Properly And To Be Able To Walk After

### Actual behavior

It Opens And Closes But Has Cursor Still On Screen And Character Cant Move Or Open Phone Again

### Last Updated

Today

### Custom Resources

qb-phone (iphone-14)

### Resource Rename

iphone

**Comment by adweex** [comment]
First of all:
qb-phone is included in the recipe and available as a resource.
However renaming the resource to iphone might cause unusual behaviour.
This Issue should be in qb-phone then, not in the core. https://github.com/Qbox-project/qb-phone

I downloaded the resource and it works fine with the up to date qbox build, so there is a high chance that the problem is caused by renaming the resource.

And i recommend you using npwd instead of qb-phone.

**Comment by BerkieBb** [comment]
I'm starting npwd integration into qbox now, soon :tm:
